### PR TITLE
Detect desynchronization

### PR DESCRIPTION
**Pull request by job**
Modeled after https://www.ietf.org/archive/id/draft-ietf-sidrops-rrdp-desynchronization-00.html

### CODE REVIEW

**Comment by job** [comment]
The wording might need a bit of wordsmithing, the goal is not to endlessly cache delta serials & hashes, but just check for the last 100 or 200 whether the server is rewriting history. In the RPKI RRDP this approach has proven useful

**Comment by mxsasha** [comment]
Might edit words a bit, but it's a good scenario to detect, and I think this approach is light enough to expect the client to run every minute.

**Comment by mxsasha** [comment]
Rephrased a bit to make clear what the exact comparison is. And changed client behaviour to just reject on mismatch: it indicates something very wrong with the server, and rejecting further updates and logging errors seems like a better approach.

**Comment by job** [comment]
The advantage of switching to the Snapshot is that it automatically resets the state to something consistent. I think this auto repair is desirable over "halt and catch fire", because ultimately the administrator will want to reset the state anyway. So logging an issue and automatic remediation would be my preference, just like is done in RRDP

**Comment by mxsasha** [comment]
But it resets the state to something consistent generated by a really broken nrtmv4 server implementation. If we know the server can't generate correct deltas, what makes us think it will generate a correct snapshot? Why trust anything it says until it is actually fixed?

**Pull request merged**
